### ISSUE TITLE
`columnCount` is already defined for GridLayout support library

### ISSUE THREAD

**Issue by letientai299** [ISchwarz23/SortableTableView#18]
Hi, 

I've just notice that my project cannot be compiled if we try to use both GridLayout and SortableTableView due to this issue.  Anyway work around to use both libraries?

Thanks.

**Comment by ISchwarz23** [comment]
Hi,

as I don't know the reason for this error I'm not able to give an Workaround solution. Could you please post thr complete StackTrace? Thanks!

Best regards

**Comment by letientai299** [comment]
Hi @ISchwarz23 ,

To reproduce, we just need to add those two lines into `build.gradle`, then perform sync with gradle files.

```groovy
compile 'com.android.support:gridlayout-v7:23.2.1'
compile 'de.codecrafters.tableview:tableview:1.0.1'
```

Here is the message from `:app:processDebugResources`:
```logcat
~/temp/App/app/build/intermediates/res/merged/debug/values/values.xml:129 : AAPT: Attribute "columnCount" has already been defined
:app:processDebugResources FAILED
```

And following is the stacktrace for `./gradlew
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugResources'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/letientai299/Software/Installed/Android/sdk/build-tools/23.0.2/aapt'' finished with non-zero exit value 1
	at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:147)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:98)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more
Caused by: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/letientai299/Software/Installed/Android/sdk/build-tools/23.0.2/aapt'' finished with non-zero exit value 1
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:42)
	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:919)
	at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:138)
	... 22 more
Caused by: org.gradle.process.internal.ExecException: Process 'command '/home/letientai299/Software/Installed/Android/sdk/build-tools/23.0.2/aapt'' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
	at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:40)
	... 24 more
```

Thanks.

**Comment by ISchwarz23** [comment]
Hi @letientai299,

unfortunately I don't think there is a workaround, as both libraries are providing an Attribute called 'columnCount'. As this issue is already accuring in the 'processDebugResources' Task there is no workaround possible in the code.  
As I also do not want to rename the attribute (because this will break the API and will lead to compilation errors on upgrading) I need to find a better solution (is there is one). Meanwhile my library can not be used in projects which also depend on the 'GridLayout' :-(

**Comment by ciskeboekelo** [comment]
IMHO you should rename anyway. I've seen a few libraries do it before, it's not at all hard to change it when upgrading, and It's the only way to fix this I think. It is also recommended by Xavier Ducrohet (Tech Lead for the Android SDK at Google)  "We recommend devs to use different prefixes for the resources in each library." and "There is no namespace trick because for the purpose of your app, all the resources are merged together in a single pool in the same namespace" (see https://groups.google.com/forum/#!topic/adt-dev/HeM0aptfddY )

**Comment by ISchwarz23** [comment]
Yes, you are right. I will create a release 2.0.0 (to indicate the api change) which has a prefix for all available xml properties. This will force the users of this library to adapt their code by changing to version 2.0.0 but then this library does not clash with other libs anymore.

**Comment by ISchwarz23** [comment]
Enjoy GridLayout and TableView in the same project. Just use the new release :)
`compile 'de.codecrafters.tableview:tableview:2.0.0'`
